parameters:

  dataGridTemplateName: AcmeDataGridBundle:Datagrid:blocks.html.twig

services:

  acme.twig.datagrid_extension:
    class: Acme\DataGridBundle\Twig\Extension\DataGridExtension
    calls:
      - [setTemplateName, [%dataGridTemplateName%]]
    tags:
      - { name: twig.extension }

  services.datagrid.entity_service:
    class: Acme\DataGridBundle\Services\DataGrid\EntityService
    arguments: [@doctrine]

  service.datagrid.datagrid_service:
    class: Acme\DataGridBundle\Services\DataGrid\DataGridService
    arguments: [@services.datagrid.entity_service]
